# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_complete <- function(pop_size, starting_freq, sd_starting_freq, introductions, removal, number_of_generations, replicates, K, morgan, nesting_risk, nest_failure_rate, establishment_burnin, seed, max_age, use_simple, verbose, clutch_size_mean, clutch_size_sd, smin, smax, p, b, sex_ratio_put, sex_ratio_pull, sex_ratio_offspring, put_ancestry, pull_ancestry, use_random_mating, extra_pair_copulation, return_genetics) {
    .Call('_simRestore_simulate_complete', PACKAGE = 'simRestore', pop_size, starting_freq, sd_starting_freq, introductions, removal, number_of_generations, replicates, K, morgan, nesting_risk, nest_failure_rate, establishment_burnin, seed, max_age, use_simple, verbose, clutch_size_mean, clutch_size_sd, smin, smax, p, b, sex_ratio_put, sex_ratio_pull, sex_ratio_offspring, put_ancestry, pull_ancestry, use_random_mating, extra_pair_copulation, return_genetics)
}

